// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5eVRr5HhUbUxjmPrAa4Lu5u_9YQEFw2g',
    appId: '1:1091221758432:web:50a438b6d73dde97238b85',
    messagingSenderId: '1091221758432',
    projectId: 'drive-easy-8b191',
    authDomain: 'drive-easy-8b191.firebaseapp.com',
    databaseURL: 'https://drive-easy-8b191-default-rtdb.firebaseio.com',
    storageBucket: 'drive-easy-8b191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZmzhoi8bg7sveU0v2x6AxaRcsdrCRVg',
    appId: '1:1091221758432:android:0d6649d12d6f52ab238b85',
    messagingSenderId: '1091221758432',
    projectId: 'drive-easy-8b191',
    databaseURL: 'https://drive-easy-8b191-default-rtdb.firebaseio.com',
    storageBucket: 'drive-easy-8b191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTKsXLRDVv7b427kwR_WWkCVCiXar56k',
    appId: '1:1091221758432:ios:c4ab5b6158c7825d238b85',
    messagingSenderId: '1091221758432',
    projectId: 'drive-easy-8b191',
    databaseURL: 'https://drive-easy-8b191-default-rtdb.firebaseio.com',
    storageBucket: 'drive-easy-8b191.firebasestorage.app',
    iosBundleId: 'com.mkawasmi.driveeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTKsXLRDVv7b427kwR_WWkCVCiXar56k',
    appId: '1:1091221758432:ios:c4ab5b6158c7825d238b85',
    messagingSenderId: '1091221758432',
    projectId: 'drive-easy-8b191',
    databaseURL: 'https://drive-easy-8b191-default-rtdb.firebaseio.com',
    storageBucket: 'drive-easy-8b191.firebasestorage.app',
    iosBundleId: 'com.mkawasmi.driveeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5eVRr5HhUbUxjmPrAa4Lu5u_9YQEFw2g',
    appId: '1:1091221758432:web:9b2e8a0c0f5da74d238b85',
    messagingSenderId: '1091221758432',
    projectId: 'drive-easy-8b191',
    authDomain: 'drive-easy-8b191.firebaseapp.com',
    databaseURL: 'https://drive-easy-8b191-default-rtdb.firebaseio.com',
    storageBucket: 'drive-easy-8b191.firebasestorage.app',
  );
}
